In [1]:
import pandas as pd
from pymongo import MongoClient

In [2]:
# connect to workstation mongoDB, set db to the table view, the collection to bin
client = MongoClient('localhost', 27017)
db = client.TableView
collection = db["bin_NHCFV"]

In [3]:
df_bin = pd.read_csv("binTable.NHCFV", sep="\t")

In [5]:
df_bin.head()

  #Chromosome  Start    End HiC Interactions ATAC ChromHMM Footprinting
0        chr1      0   2000                .    .        .            .
1        chr1   2000   4000                .    .        .            .
2        chr1   4000   6000                .    .        .            .
3        chr1   6000   8000                .    .        .            .
4        chr1   8000  10000                .    .        .            .

In [6]:
df_bin[df_bin["HiC Interactions"] != "."]

,#Chromosome,Start,End,HiC Interactions,ATAC,ChromHMM,Footprinting
50,chr1,100000,102000,chr1-268000(1.000000),.,25_Quies(100000-102000),.
134,chr1,268000,270000,chr1-100000(1.000000),.,19_DNase(268000-268049);25_Quies(268049-270000),.
378,chr1,756000,758000,chr1-223974000(1.000000),.,25_Quies(756000-758000),.
389,chr1,778000,780000,chr1-824000(1.000000);chr1-223992000(1.000000),778575-778845(13.54312),4_PromD2(778000-778020);2_PromU(778020-778220)...,"mbpsid:MA0024.3,TF:E2F1,region:1:778599-778611..."
392,chr1,784000,786000,chr1-224008000(1.000000),.,25_Quies(784000-786000),.
...,...,...,...,...,...,...,...
1528856,chrY,26648000,26650000,chrY-26666000(1.000000),.,.,.
1528857,chrY,26650000,26652000,chrY-26668000(0.000000);chrY-26666000(1.000000),.,.,.
1528861,chrY,26658000,26660000,chrY-26668000(1.000000),.,.,.
1528865,chrY,26666000,26668000,chrY-26650000(1.000000);chrY-26648000(1.000000...,.,.,.
1528866,chrY,26668000,26670000,chrY-26650000(0.000000);chrY-26658000(1.000000),.,.,.

In [7]:
for i, r in df_bin.iterrows():
    document = {}
    document["Chr"] = r["#Chromosome"]
    document["Start"] = r["Start"]
    document["End"] = r["End"]
    document["HiC_interactions"] = r["HiC Interactions"].split(";")
    document["ATAC"] = r["ATAC"].split(";")
    document["ChromHMM"] = r["ChromHMM"].split(";")
    document["Footprinting"] = r["Footprinting"].split(";")
    collection.insert_one(document)

In [8]:
collection.create_index("Start")

'Start_1'

In [9]:
collection.count()

<ipython-input-9-7c4bc5758cb0>:1: DeprecationWarning: count is deprecated. Use estimated_document_count or count_documents instead. Please note that $where must be replaced by $expr, $near must be replaced by $geoWithin with $center, and $nearSphere must be replaced by $geoWithin with $centerSphere
  collection.count()

1544146